# Предложения
## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
//Authorization: Bearer
###

## Добавить новое предложение
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
  "title": "66 - Lorem ipsum dolor sit amet.",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "postDate": "2023-11-01T14:14:14.333Z",
  "city": "Amsterdam",
  "preview": "https://www.paris.com/imagePre.jpg",
  "photos": ["https://www.paris.com/image1.jpg", "https://www.paris.com/image2.jpg", "https://www.paris.com/image3.jpg", "https://www.paris.com/image4.jpg", "https://www.paris.com/image5.jpg", "https://www.paris.com/image6.jpg"],
  "isPremium": true,
  "housingType": "House",
  "roomCount": 1,
  "guestCount": 7,
  "rentPrice": 101,
  "features": ["Breakfast", "Washer"],
  "location": ["51.225402", "6.776314"]
}

###

## Получение информации по идентификатору

GET http://localhost:4000/offers/654b77c391e6920f44ff84fe HTTP/1.1

###

## Обновить предложение

PATCH http://localhost:4000/offers/6549ea7f44dca11fca679ad1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
  "title": "title-Lorem ipsum dolor sit amet.",
  "description": "Проверка обновления. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "city": "Amsterdam"
}

###

## Удалить предложение по идентификатору

DELETE http://localhost:4000/offers/654c6a3f6fc5a7620465a223 HTTP/1.1
Authorization: Bearer

###

## Получить премиальные предложения для города

GET http://localhost:4000/offers/Amsterdam/premium HTTP/1.1

###

## Загрузить изображение для объявления
POST http://localhost:4000/offers/65258514a30fc6ef77c0edf7/preview HTTP/1.1
Authorization: Bearer
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview"; filename="screen.png"
Content-Type: image/png

< /Users/spider_net/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
