export type MockServerData = {
  title: string[];
  description: string[];
  // postDate: Date;
  city: string[];
  preview: string[];
  photos: string[];
  // isPremium: boolean;
  // isFavourite: boolean;
  // rating: number;
  housingType: string[];
  // roomCount: number;
  // guestCount: number;
  // rentPrice: number;
  features: string[];
  // author: string[];
  name: string[];
  email: string[];
  avatar: string[];
  // commentsCount: number;
  // location: Coords;
};
